"""Constants for Xiaomi S400 Local."""

DOMAIN = "xiaomi_s400_local"

CONF_BINDKEY = "bindkey"
CONF_TOKEN = "token"
CONF_FAILURE_THRESHOLD = "failure_threshold"
CONF_ACTIVE_RETRY_INTERVAL = "active_retry_interval"
CONF_GATT_TIMEOUT = "gatt_timeout"
CONF_CMTP_WAIT_TIMEOUT = "cmtp_wait_timeout"

DEFAULT_FAILURE_THRESHOLD = 5
DEFAULT_ACTIVE_RETRY_INTERVAL = 15.0
DEFAULT_GATT_TIMEOUT = 8.0
DEFAULT_CMTP_WAIT_TIMEOUT = 5.0
CONF_PRODUCT_ID = "product_id"
CONF_DID = "did"
MIBEACON_UUID = "0000fe95-0000-1000-8000-00805f9b34fb"
S400_PRODUCT_IDS = {0x30D9, 0x3BD5, 0x48CF}
